// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Program = 1,
  Word = 2,
  Parenthesized = 5,
  Postfix = 6,
  Anagram = 7,
  Reverse = 9,
  Lookup = 11,
  Call = 13,
  OpName = 15,
  ArgList = 16,
  Argument = 17,
  Number = 18,
  Index = 21,
  Prefix = 23,
  Concat = 25,
  Intersect = 27
