// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "%vOVQPOOObQPO'#C^OOQO'#C^'#C^OVQPO'#CaQ!VQPOOO!nQPO'#CsOOQO'#C}'#C}O!sQPO,58{OOQO'#Cc'#CcOOQO'#Ce'#CeOOQO'#Cg'#CgOOQO,58|,58|O!zQPO,59TO#PQPO,59]OVQPO,59aOVQPO,59cOVQPO,59_OOQO1G.g1G.gOOQO'#Ck'#CkO#UQPO1G.oO#yQPO1G.wO$aQPO1G.{O$tQPO1G.}O%XQPO1G.yO%lQPO'#ClOOQO7+$Z7+$ZOOQO7+$c7+$cO%}QPO'#CmOOQO'#Cm'#CmOOQO,59W,59WO&XQPO,59WO%oQPO'#CyO&aQPO1G.rOOQO1G.r1G.rOOQO,59e,59eOOQO-E6w-E6wOOQO7+$^7+$^",
  stateData: "&i~OpOS~OSROrPOsQO~OWQXYQX[QX^QXfQXh_XjQXlQXnQXRQXcQX~OWWOYXO[YO^[Of]Oj^Ol_O~Oh`O~ORaO~P!VOrbO~ObdO~OShOW]iY]i[]i^]if]ij]il]in]iR]ic]i~OdjO~OWWOYXO[YO^[Of]O~OjiiliiniiRiicii~P$OOj^OlkinkiRkicki~P$OOjgilgingiRgicgi~P$OORmOSROblOrPOsQO~ORaXcaX~P!VORqOcoO~ORtOcoO~O",
  goto: "#UrPPsPPss|P|P|PsP!U!b!ePPPsPsPsPsP!kPPP!q_UOR^_`ho]ZSVefgk^TOR^_`hoRc[RicQnhRroQpnRspQSOQVRQe^Qf_Qg`Tkho",
  nodeNames: "⚠ Program Word ) ( Parenthesized Postfix Anagram * Reverse < Lookup ? Call . OpName ArgList Argument Number , ] Index [ Prefix : Concat + Intersect =",
  maxTerm: 35,
  nodeProps: [
    ["openedBy", 3,"("],
    ["closedBy", 4,")"]
  ],
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "&U~RkX^!vpq!vrs#kxy$]yz$bz{$g{|$l|}$q}!O$v!O!P%U!Q![$|![!]%Z!^!_%`!_!`%e!a!b%j!c!}%o!}#O%z#P#Q&P#T#o%o#y#z!v$f$g!v#BY#BZ!v$IS$I_!v$I|$JO!v$JT$JU!v$KV$KW!v&FU&FV!v~!{Yp~X^!vpq!v#y#z!v$f$g!v#BY#BZ!v$IS$I_!v$I|$JO!v$JT$JU!v$KV$KW!v&FU&FV!v~#nRpq#w!c!}#w#T#o#w~#zSpq#wrs$W!c!}#w#T#o#w~$]Os~~$bOS~~$gOR~~$lOW~~$qOj~~$vOc~~$yP!Q![$|~%RPb~!Q![$|~%ZO^~~%`Oh~~%eOY~~%jOl~~%oO[~~%tQr~!c!}%o#T#o%o~&POf~~&UOd~",
  tokenizers: [0],
  topRules: {"Program":[0,1]},
  tokenPrec: 0
})
